apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fotball-frontend
  namespace: banan2
spec:
  ingresses:
    - https://fotballappen.sandbox.test-nais.cloud.nais.io
  image: {{image}}
  port: 8080
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
